import streamlit as st
import pandas as pd
import joblib
import numpy as np
from fpdf import FPDF # Library baru untuk bikin PDF
import base64

# ==========================================
# 1. KONFIGURASI HALAMAN
# ==========================================
st.set_page_config(
    page_title="SatriaAItech Valuations",
    page_icon="🏢",
    layout="wide",
    initial_sidebar_state="collapsed"
)

st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;800&display=swap');
    html, body, [class*="css"] { font-family: 'Plus Jakarta Sans', sans-serif; }
    .stApp { background-color: #0e1117; }
    div.stButton > button:first-child {
        background: linear-gradient(90deg, #FF4B2B 0%, #FF416C 100%);
        color: white; border: none; border-radius: 8px; padding: 12px 20px; font-weight: 600; width: 100%;
    }
    div.stButton > button:first-child:hover { transform: translateY(-2px); }
    [data-testid="stMetricValue"] { color: #00ff9d !important; font-size: 28px !important; }
    </style>
""", unsafe_allow_html=True)

# ==========================================
# 2. LOGIKA PDF GENERATOR (FITUR BARU)
# ==========================================
def create_pdf(provinsi, lt, lb, kt, km, harga, cicilan):
    pdf = FPDF()
    pdf.add_page()
    
    # Header SatriaAItech
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "SatriaAItech Property Valuation", ln=True, align='C')
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 10, "Enterprise AI Valuation System v3.1", ln=True, align='C')
    pdf.line(10, 30, 200, 30)
    
    # Isi Laporan
    pdf.ln(20)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, f"Laporan Valuasi Properti: {provinsi}", ln=True)
    
    pdf.set_font("Arial", '', 11)
    pdf.cell(0, 8, f"Luas Tanah: {lt} m2", ln=True)
    pdf.cell(0, 8, f"Luas Bangunan: {lb} m2", ln=True)
    pdf.cell(0, 8, f"Spesifikasi: {kt} K.Tidur / {km} K.Mandi", ln=True)
    
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, f"Estimasi Harga Pasar: Rp {harga:,.0f}", ln=True)
    
    pdf.set_font("Arial", '', 11)
    pdf.cell(0, 8, f"Estimasi Cicilan KPR (15 Thn): Rp {cicilan:,.0f} / bulan", ln=True)
    
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 5, "Disclaimer: Harga ini adalah estimasi AI (Artificial Intelligence) dan bukan harga final transaksi.", ln=True)
    pdf.cell(0, 5, "Generated by SatriaAItech System.", ln=True)
    
    return pdf.output(dest='S').encode('latin-1')

# ==========================================
# 3. LOGIKA MODEL
# ==========================================
@st.cache_resource
def load_model():
    try: return joblib.load('model_rumah_xgboost.pkl')
    except: return None

model = load_model()

faktor_provinsi = {
    "DKI Jakarta (Premium)": {'lat': -6.20, 'lon': 106.84, 'multiplier': 550000},
    "Bali (Tourist Area)": {'lat': -8.40, 'lon': 115.18, 'multiplier': 450000},
    "Kalimantan Timur (IKN - Future)": {'lat': -0.50, 'lon': 117.15, 'multiplier': 400000},
    "Jawa Barat (Bandung/Bekasi)": {'lat': -6.91, 'lon': 107.60, 'multiplier': 350000},
    "Jawa Timur (Surabaya/Malang)": {'lat': -7.25, 'lon': 112.79, 'multiplier': 320000},
    "Sulawesi Selatan (Makassar)": {'lat': -5.14, 'lon': 119.43, 'multiplier': 300000},
    "DI Yogyakarta (Cultural)": {'lat': -7.79, 'lon': 110.36, 'multiplier': 280000},
    "Jawa Tengah (Semarang/Solo)": {'lat': -6.96, 'lon': 110.41, 'multiplier': 250000},
}

def update_template():
    pilihan = st.session_state.template_selector
    if pilihan == "Tipe 36 (Subsidi)":
        st.session_state.lb, st.session_state.lt = 36, 60
        st.session_state.kt, st.session_state.km = 2, 1
    elif pilihan == "Tipe 45 (Standard)":
        st.session_state.lb, st.session_state.lt = 45, 90
        st.session_state.kt, st.session_state.km = 2, 1
    elif pilihan == "Tipe 70 (Family)":
        st.session_state.lb, st.session_state.lt = 70, 120
        st.session_state.kt, st.session_state.km = 3, 2
    elif pilihan == "Tipe 120 (Luxury)":
        st.session_state.lb, st.session_state.lt = 120, 200
        st.session_state.kt, st.session_state.km = 4, 3

if 'lb' not in st.session_state: st.session_state.lb = 45
if 'lt' not in st.session_state: st.session_state.lt = 90
if 'kt' not in st.session_state: st.session_state.kt = 2
if 'km' not in st.session_state: st.session_state.km = 1

# ==========================================
# 4. LAYOUT FRONTEND
# ==========================================
c_head1, c_head2 = st.columns([0.5, 4])
with c_head1: st.image("https://cdn-icons-png.flaticon.com/512/1040/1040993.png", width=60)
with c_head2:
    st.title("SatriaAItech Properti")
    st.caption("Enterprise Real Estate Valuation System v3.2 (PDF Report)")
st.markdown("---")

c_left, c_right = st.columns([1, 1.5], gap="large")

with c_left:
    with st.container(border=True):
        st.subheader("⚙️ Parameter Properti")
        pilihan_provinsi = st.selectbox("📍 Pilih Wilayah", list(faktor_provinsi.keys()))
        data_lokasi = faktor_provinsi[pilihan_provinsi]
        
        st.markdown("---")
        st.selectbox("⚡ Template Cepat:", ["Custom", "Tipe 36 (Subsidi)", "Tipe 45 (Standard)", "Tipe 70 (Family)", "Tipe 120 (Luxury)"], key='template_selector', on_change=update_template)
        st.markdown("<br>", unsafe_allow_html=True)
        
        c1, c2 = st.columns(2)
        with c1:
            luas_tanah = st.number_input("📐 L. Tanah (m²)", min_value=30, step=5, key='lt')
            kamar_tidur = st.number_input("🛏️ K. Tidur", min_value=1, step=1, key='kt')
        with c2:
            luas_bangunan = st.number_input("🏠 L. Bangunan (m²)", min_value=21, step=5, key='lb')
            kamar_mandi = st.number_input("🚿 K. Mandi", min_value=1, step=1, key='km')

    simulasi_medinc = (luas_bangunan / 15) 
    input_model = {
        'MedInc': simulasi_medinc, 'HouseAge': 15, 
        'AveRooms': luas_tanah / 15, 'AveBedrms': kamar_tidur,
        'Population': 1000, 'AveOccup': 3,
        'Latitude': 34.0, 'Longitude': -118.2,
        'Bedrooms_Ratio': kamar_tidur / (luas_tanah/15) if luas_tanah > 0 else 0
    }
    features = pd.DataFrame(input_model, index=[0])

with c_right:
    with st.container(border=True):
        st.subheader("📊 Hasil Valuasi AI")
        st.map(pd.DataFrame({'lat': [data_lokasi['lat']], 'lon': [data_lokasi['lon']]}), zoom=6, height=200)
        st.markdown("<br>", unsafe_allow_html=True)
        
        if st.button('🚀 HITUNG HARGA PASAR', use_container_width=True):
            if model is not None:
                base_pred = model.predict(features)[0]
                harga_final = base_pred * data_lokasi['multiplier'] * 1000
                if harga_final < 50000000: harga_final = 50000000
                
                st.markdown("---")
                c_res1, c_res2 = st.columns([2,1])
                with c_res1: st.metric("Estimasi Harga", f"Rp {harga_final:,.0f}", "Akurasi AI")
                with c_res2: st.metric("Harga / m²", f"Rp {(harga_final / luas_bangunan)/1000000:,.1f} Jt")
                
                with st.container(border=True):
                    st.markdown("#### 🏦 Simulasi Cicilan (8.5%)")
                    dp = harga_final * 0.2
                    loan = harga_final - dp
                    rate = 0.085 / 12
                    tenor_bln = 15 * 12
                    cicilan = (loan * rate) / (1 - (1 + rate)**(-tenor_bln))
                    
                    k1, k2, k3 = st.columns(3)
                    k1.metric("DP (20%)", f"{dp/1000000:,.0f} Jt")
                    k2.metric("Tenor", "15 Thn")
                    k3.metric("Cicilan", f"{cicilan/1000000:,.1f} Jt")

                # --- BAGIAN DOWNLOAD PDF & WA ---
                col_btn1, col_btn2 = st.columns(2)
                
                # 1. Generate PDF
                pdf_bytes = create_pdf(pilihan_provinsi, luas_tanah, luas_bangunan, kamar_tidur, kamar_mandi, harga_final, cicilan)
                
                with col_btn1:
                    st.download_button(
                        label="📄 Download Laporan PDF",
                        data=pdf_bytes,
                        file_name="Laporan_SatriaAItech.pdf",
                        mime="application/pdf",
                        use_container_width=True
                    )

                # 2. WhatsApp
                with col_btn2:
                    pesan = f"Halo SatriaAItech, cek properti {pilihan_provinsi} estimasi Rp {harga_final:,.0f}."
                    link_wa = f"https://wa.me/628123456789?text={pesan.replace(' ', '%20')}"
                    st.link_button("📞 Chat WA", link_wa, type="primary", use_container_width=True)
            else:
                st.error("Model file (.pkl) not found.")

st.markdown("<div style='text-align:center; margin-top:30px; color:#555;'><small>© 2025 SatriaAItech Enterprise System.</small></div>", unsafe_allow_html=True)